# Generated by Django 4.1.3 on 2022-12-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name_plural': 'social media'},
        ),
        migrations.AddField(
            model_name='profile',
            name='team_member',
            field=models.BooleanField(default=False),
        ),
    ]
