# Generated by Django 4.1.3 on 2022-12-05 08:56

import acct.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0003_remove_profile_first_name_remove_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to=acct.models.user_profile_upload),
        ),
    ]
