# Generated by Django 4.1.3 on 2022-12-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='bootstrap_icon_class',
            field=models.CharField(max_length=20),
        ),
    ]
